# Generated by Django 5.1.2 on 2024-10-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='parent',
        ),
    ]
